import { Hono } from 'hono';
import { cors } from 'hono/cors';
import { secureHeaders } from 'hono/secure-headers';
import { HTTPException } from 'hono/http-exception';
import { ZodError, z } from 'zod';
import type { AppEnv, NotificationJob } from './types';
import { announcementSchema, credentials, guestSchema, json, rsvpSchema, scheduleSchema } from './validation';
import { clearCookie, cookie, getCookie, hashPassword, hmacSha512, randomToken, sha256, uid, verifyPassword } from './security';

const app = new Hono<AppEnv>();
const nowIso=()=>new Date().toISOString();
const expires=(days=30)=>new Date(Date.now()+days*86400000).toISOString();
const audit=async(db:D1Database,eventId:string|null,actor:string|null,action:string,type:string,entity:string|null,requestId:string,meta:unknown={})=>db.prepare('INSERT INTO audit_logs(id,event_id,actor_id,action,entity_type,entity_id,metadata_json,request_id) VALUES(?,?,?,?,?,?,?,?)').bind(uid('aud'),eventId,actor,action,type,entity,JSON.stringify(meta),requestId).run();

app.use('*', async (c,next)=>{c.set('requestId',c.req.header('x-request-id')||crypto.randomUUID());await next();c.header('x-request-id',c.get('requestId'));});
app.use('/api/*', secureHeaders());
app.use('/api/*', cors({origin:(origin,c)=>origin===c.env.APP_ORIGIN||c.env.APP_ENV==='development'?origin:'',credentials:true,allowMethods:['GET','POST','PUT','PATCH','DELETE','OPTIONS'],allowHeaders:['Content-Type','Idempotency-Key','X-Request-Id']}));

async function rateLimit(c:any,next:any){const ip=c.req.header('cf-connecting-ip')||c.req.header('x-forwarded-for')?.split(',')[0]||'local';const window=Math.floor(Date.now()/60000),key=`rl:${await sha256(ip)}:${c.req.path}:${window}`;const count=Number(await c.env.CACHE.get(key)||0)+1;if(count>30)throw new HTTPException(429,{message:'Too many requests. Please try again shortly.'});await c.env.CACHE.put(key,String(count),{expirationTtl:120});await next();}
async function authenticate(c:any,next:any){const raw=getCookie(c.req.header('cookie'),'invibox_session');if(!raw)throw new HTTPException(401,{message:'Authentication required'});const hash=await sha256(raw+(c.env.SESSION_PEPPER||''));const row=await c.env.DB.prepare("SELECT user_id FROM sessions WHERE token_hash=? AND expires_at > datetime('now')").bind(hash).first() as {user_id:string}|null;if(!row)throw new HTTPException(401,{message:'Session expired'});c.set('userId',row.user_id);await next();}
async function ownEvent(c:any,eventId:string){const row=await c.env.DB.prepare("SELECT e.* FROM events e LEFT JOIN event_members m ON m.event_id=e.id AND m.user_id=? WHERE e.id=? AND (e.owner_id=? OR m.role IN ('owner','admin','designer','guest_manager','checkin_staff','viewer'))").bind(c.get('userId'),eventId,c.get('userId')).first();if(!row)throw new HTTPException(404,{message:'Event not found'});return row;}

app.use('/api/v1/auth/*',rateLimit);
app.use('/api/v1/public/rsvp',rateLimit);
app.use('/api/v1/public/analytics',rateLimit);
app.get('/api/v1/health',c=>c.json({ok:true,service:'invibox-api',environment:c.env.APP_ENV,time:nowIso()}));
app.post('/api/v1/auth/register',async c=>{const body=await json(c.req.raw,credentials.extend({name:z.string().trim().min(2).max(100)}));const exists=await c.env.DB.prepare('SELECT id FROM users WHERE email=?').bind(body.email).first();if(exists)throw new HTTPException(409,{message:'An account already exists for this email'});const id=uid('usr'),token=randomToken();await c.env.DB.batch([c.env.DB.prepare('INSERT INTO users(id,email,password_hash,full_name) VALUES(?,?,?,?)').bind(id,body.email,await hashPassword(body.password),body.name),c.env.DB.prepare('INSERT INTO sessions(id,user_id,token_hash,expires_at,user_agent) VALUES(?,?,?,?,?)').bind(uid('ses'),id,await sha256(token+(c.env.SESSION_PEPPER||'')),expires(),c.req.header('user-agent')||null)]);c.header('Set-Cookie',cookie(token));return c.json({user:{id,email:body.email,name:body.name}},201)});
app.post('/api/v1/auth/login',async c=>{const body=await json(c.req.raw,credentials);const user=await c.env.DB.prepare('SELECT id,email,password_hash,full_name FROM users WHERE email=?').bind(body.email).first<any>();if(!user||!(await verifyPassword(body.password,user.password_hash)))throw new HTTPException(401,{message:'Invalid email or password'});const token=randomToken();await c.env.DB.prepare('INSERT INTO sessions(id,user_id,token_hash,expires_at,user_agent) VALUES(?,?,?,?,?)').bind(uid('ses'),user.id,await sha256(token+(c.env.SESSION_PEPPER||'')),expires(),c.req.header('user-agent')||null).run();c.header('Set-Cookie',cookie(token));return c.json({user:{id:user.id,email:user.email,name:user.full_name}})});
app.post('/api/v1/auth/logout',authenticate,async c=>{const raw=getCookie(c.req.header('cookie'),'invibox_session')!;await c.env.DB.prepare('DELETE FROM sessions WHERE token_hash=?').bind(await sha256(raw+(c.env.SESSION_PEPPER||''))).run();c.header('Set-Cookie',clearCookie());return c.json({ok:true})});
app.get('/api/v1/auth/me',authenticate,async c=>{const user=await c.env.DB.prepare('SELECT id,email,full_name AS name,platform_role AS role FROM users WHERE id=?').bind(c.get('userId')).first();return c.json({user})});

app.post('/api/v1/demo/bootstrap',async c=>{if(c.env.DEMO_MODE!=='true')throw new HTTPException(404);const email='demo@invibox.app';let user=await c.env.DB.prepare('SELECT id,email,full_name FROM users WHERE email=?').bind(email).first<any>();if(!user){const id=uid('usr');await c.env.DB.prepare('INSERT INTO users(id,email,password_hash,full_name,email_verified_at) VALUES(?,?,?,?,?)').bind(id,email,await hashPassword(randomToken()),'Amaka Okafor',nowIso()).run();user={id,email,full_name:'Amaka Okafor'}}let event=await c.env.DB.prepare('SELECT id FROM events WHERE owner_id=? AND slug=?').bind(user.id,'amaka-chidi').first<any>();let guestToken='kemi-demo-invitation-token-2026';if(!event){const eventId=uid('evt'),groupId=uid('grp'),occasionIds=[uid('occ'),uid('occ'),uid('occ')];event={id:eventId};await c.env.DB.batch([
 c.env.DB.prepare("INSERT INTO events(id,owner_id,slug,title,event_type,lifecycle,starts_at,timezone,location,visibility,published_at,settings_json,theme_json) VALUES(?,?,?,?,?,'published',?,?,?,?,?,?,?)").bind(eventId,user.id,'amaka-chidi','Amaka & Chidi','wedding','2026-12-19T10:00:00+01:00','Africa/Lagos','Lagos, Nigeria','guest_specific',nowIso(),JSON.stringify({capabilities:['rsvp','seating','transport','accommodation','gifts','memories']}),JSON.stringify({primary:'#343931',accent:'#9b7450'})),
 c.env.DB.prepare("INSERT INTO event_members(event_id,user_id,role) VALUES(?,?,'owner')").bind(eventId,user.id),c.env.DB.prepare('INSERT INTO guest_groups(id,event_id,name,kind) VALUES(?,?,?,?)').bind(groupId,eventId,'Friends','friends'),
 ...[['Traditional ceremony','2026-12-19T10:00:00+01:00','The Monarch Hall, Lekki','Family & VIP'],['White wedding','2026-12-19T13:30:00+01:00','Grace Pavilion, Victoria Island','All guests'],['Reception & dinner','2026-12-19T17:00:00+01:00','The Grand Ballroom','All guests']].map((x,i)=>c.env.DB.prepare('INSERT INTO occasions(id,event_id,title,starts_at,venue_name,address,audience,sort_order) VALUES(?,?,?,?,?,?,?,?)').bind(occasionIds[i],eventId,x[0],x[1],x[2],x[2],x[3],i)),
 ]);
 const guestRows=[['Kemi Adeyemi','attending',2,'Jollof & chicken','T12',1],['Tunde Okafor','attending',1,'Vegetarian','T04',0],['Nneka & Emeka Obi','pending',2,null,null,0],['Ibrahim Bello','declined',1,null,null,0],['The Afolabi Family','attending',5,'Mixed','T01',0],['Damilola George','pending',1,null,null,0],['Chisom Nwosu','attending',2,'Jollof & fish','T08',1],['Aunty Bola','attending',3,'Mixed','T02',0]];const statements=[];for(let i=0;i<guestRows.length;i++){const x=guestRows[i],gid=uid('gst'),token=i===0?guestToken:randomToken();statements.push(c.env.DB.prepare('INSERT INTO guests(id,event_id,group_id,name,status,party_size,meal,table_name,checked_in_at,access_token_hash,access_token_hint) VALUES(?,?,?,?,?,?,?,?,?,?,?)').bind(gid,eventId,groupId,x[0],x[1],x[2],x[3],x[4],x[5]?nowIso():null,await sha256(token),token.slice(-6)));for(const oid of occasionIds)statements.push(c.env.DB.prepare('INSERT INTO guest_occasion_access(guest_id,occasion_id,rsvp_status) VALUES(?,?,?)').bind(gid,oid,x[1]==='attending'?'attending':x[1]==='declined'?'declined':'pending'))}await c.env.DB.batch(statements);
 await c.env.DB.batch([['Venue & catering',700000000,580000000],['Decor & florals',250000000,210000000],['Photo & video',180000000,145000000]].map(x=>c.env.DB.prepare('INSERT INTO budgets(id,event_id,category,budget_minor,spent_minor) VALUES(?,?,?,?,?)').bind(uid('bdg'),eventId,x[0],x[1],x[2])));
 }
 const tableCount=await c.env.DB.prepare('SELECT COUNT(*) AS count FROM seating_tables WHERE event_id=?').bind(event.id).first<{count:number}>();if(!tableCount?.count){await c.env.DB.batch([['T01','round',10,18,22],['T02','round',10,48,18],['T04','round',10,76,25],['T08','round',8,25,67],['T12','round',10,67,65]].map(t=>c.env.DB.prepare('INSERT INTO seating_tables(id,event_id,name,shape,capacity,x,y) VALUES(?,?,?,?,?,?,?)').bind(uid('tbl'),event.id,...t)))}
 const token=randomToken();await c.env.DB.prepare('INSERT INTO sessions(id,user_id,token_hash,expires_at,user_agent) VALUES(?,?,?,?,?)').bind(uid('ses'),user.id,await sha256(token+(c.env.SESSION_PEPPER||'')),expires(),c.req.header('user-agent')||null).run();c.header('Set-Cookie',cookie(token));return c.json({ok:true,eventId:event.id,slug:'amaka-chidi',guestToken})});

app.get('/api/v1/events',authenticate,async c=>{const rows=await c.env.DB.prepare("SELECT DISTINCT e.id,e.slug,e.title,e.event_type,e.lifecycle,e.starts_at,e.location FROM events e LEFT JOIN event_members m ON m.event_id=e.id WHERE e.owner_id=? OR m.user_id=? ORDER BY e.updated_at DESC").bind(c.get('userId'),c.get('userId')).all();return c.json({events:rows.results})});
app.post('/api/v1/events',authenticate,async c=>{const body=await json(c.req.raw,z.object({title:z.string().trim().min(2).max(140),eventType:z.string().trim().min(2).max(50),date:z.string().date(),location:z.string().trim().min(2).max(180),timezone:z.string().max(80).default('Africa/Lagos')}));const base=body.title.toLowerCase().normalize('NFKD').replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'').slice(0,60)||'event';let slug=base,n=1;while(await c.env.DB.prepare('SELECT id FROM events WHERE slug=?').bind(slug).first())slug=`${base}-${++n}`;const id=uid('evt');await c.env.DB.batch([c.env.DB.prepare("INSERT INTO events(id,owner_id,slug,title,event_type,lifecycle,starts_at,timezone,location,visibility) VALUES(?,?,?,?,?,'draft',?,?,?,'guest_specific')").bind(id,c.get('userId'),slug,body.title,body.eventType,`${body.date}T12:00:00`,body.timezone,body.location),c.env.DB.prepare("INSERT INTO event_members(event_id,user_id,role) VALUES(?,?,'owner')").bind(id,c.get('userId'))]);await audit(c.env.DB,id,c.get('userId'),'event.create','event',id,c.get('requestId'));return c.json({event:{id,slug,title:body.title,lifecycle:'draft'}},201)});
app.use('/api/v1/events/*',authenticate);
app.patch('/api/v1/events/:eventId',async c=>{const id=c.req.param('eventId');await ownEvent(c,id);const body=await json(c.req.raw,z.object({title:z.string().trim().min(2).max(140).optional(),eventType:z.string().max(50).optional(),lifecycle:z.enum(['draft','preview','published','active','live','completed','archived']).optional(),startsAt:z.string().datetime({offset:true}).optional(),timezone:z.string().max(80).optional(),location:z.string().max(180).optional(),visibility:z.enum(['public','private','guest_specific','password']).optional(),settings:z.record(z.string(),z.unknown()).optional(),theme:z.record(z.string(),z.unknown()).optional()}));const current=await c.env.DB.prepare('SELECT * FROM events WHERE id=?').bind(id).first<any>();await c.env.DB.prepare('UPDATE events SET title=?,event_type=?,lifecycle=?,starts_at=?,timezone=?,location=?,visibility=?,settings_json=?,theme_json=?,version=version+1,updated_at=CURRENT_TIMESTAMP,published_at=CASE WHEN ? IN (\'published\',\'active\',\'live\') AND published_at IS NULL THEN CURRENT_TIMESTAMP ELSE published_at END WHERE id=?').bind(body.title??current.title,body.eventType??current.event_type,body.lifecycle??current.lifecycle,body.startsAt??current.starts_at,body.timezone??current.timezone,body.location??current.location,body.visibility??current.visibility,body.settings?JSON.stringify(body.settings):current.settings_json,body.theme?JSON.stringify(body.theme):current.theme_json,body.lifecycle??current.lifecycle,id).run();await audit(c.env.DB,id,c.get('userId'),'event.update','event',id,c.get('requestId'),body);return c.json({ok:true})});
app.get('/api/v1/events/:eventId/snapshot',async c=>{const id=c.req.param('eventId');const event=await ownEvent(c,id);const [g,o,b,v,s,t,m,a]=await Promise.all([c.env.DB.prepare("SELECT g.id,g.name,COALESCE(gg.name,'Guests') AS 'group',g.status,g.party_size AS party,COALESCE(g.meal,'—') AS meal,g.table_name AS 'table',g.checked_in_at IS NOT NULL AS checkedIn FROM guests g LEFT JOIN guest_groups gg ON gg.id=g.group_id WHERE g.event_id=? ORDER BY g.created_at").bind(id).all(),c.env.DB.prepare("SELECT id,strftime('%H:%M',starts_at) AS time,title,venue_name AS place,audience FROM occasions WHERE event_id=? ORDER BY sort_order,starts_at").bind(id).all(),c.env.DB.prepare('SELECT * FROM budgets WHERE event_id=?').bind(id).all(),c.env.DB.prepare('SELECT * FROM vendors WHERE event_id=?').bind(id).all(),c.env.DB.prepare('SELECT * FROM experience_sections WHERE event_id=? ORDER BY sort_order').bind(id).all(),c.env.DB.prepare('SELECT st.*,COALESCE(SUM(g.party_size),0) AS assigned FROM seating_tables st LEFT JOIN guests g ON g.event_id=st.event_id AND g.table_name=st.name WHERE st.event_id=? GROUP BY st.id ORDER BY st.name').bind(id).all(),c.env.DB.prepare('SELECT id,mime_type,size_bytes,caption,status,created_at FROM media WHERE event_id=? ORDER BY created_at DESC').bind(id).all(),c.env.DB.prepare('SELECT type,COUNT(*) AS count FROM analytics_events WHERE event_id=? GROUP BY type').bind(id).all()]);return c.json({event,guests:g.results.map((x:any)=>({...x,checkedIn:Boolean(x.checkedIn),status:x.status[0].toUpperCase()+x.status.slice(1),initials:x.name.split(' ').slice(0,2).map((n:string)=>n[0]).join('').toUpperCase()})),schedule:o.results,budgets:b.results,vendors:v.results,sections:s.results,seating:t.results,media:m.results,analytics:Object.fromEntries(a.results.map((row:any)=>[row.type,row.count]))})});
app.post('/api/v1/events/:eventId/guests',async c=>{const id=c.req.param('eventId');await ownEvent(c,id);const body=await json(c.req.raw,guestSchema.omit({id:true,checkedIn:true}));let group=await c.env.DB.prepare('SELECT id FROM guest_groups WHERE event_id=? AND name=?').bind(id,body.group).first<any>();if(!group){group={id:uid('grp')};await c.env.DB.prepare('INSERT INTO guest_groups(id,event_id,name) VALUES(?,?,?)').bind(group.id,id,body.group).run()}const guestId=uid('gst'),token=randomToken();await c.env.DB.prepare('INSERT INTO guests(id,event_id,group_id,name,status,party_size,meal,table_name,access_token_hash,access_token_hint) VALUES(?,?,?,?,?,?,?,?,?,?)').bind(guestId,id,group.id,body.name,body.status.toLowerCase(),body.party,body.meal==='—'?null:body.meal,body.table||null,await sha256(token),token.slice(-6)).run();const occasions=await c.env.DB.prepare('SELECT id FROM occasions WHERE event_id=?').bind(id).all<any>();if(occasions.results.length)await c.env.DB.batch(occasions.results.map(o=>c.env.DB.prepare('INSERT INTO guest_occasion_access(guest_id,occasion_id) VALUES(?,?)').bind(guestId,o.id)));await audit(c.env.DB,id,c.get('userId'),'guest.create','guest',guestId,c.get('requestId'));return c.json({guest:{id:guestId,...body,checkedIn:false},token},201)});
app.put('/api/v1/events/:eventId/guests/sync',async c=>{const id=c.req.param('eventId');await ownEvent(c,id);const body=await json(c.req.raw,z.object({guests:z.array(guestSchema).max(5000)}));const groupCache=new Map<string,string>();const stmts=[];const keep=[];for(const g of body.guests){const gid=g.id?(g.id.startsWith('gst_')?g.id:`gst_local_${g.id}`):uid('gst');keep.push(gid);let groupId=groupCache.get(g.group);if(!groupId){const existing=await c.env.DB.prepare('SELECT id FROM guest_groups WHERE event_id=? AND name=?').bind(id,g.group).first<any>();groupId=existing?.id||uid('grp');groupCache.set(g.group,groupId!);if(!existing)stmts.push(c.env.DB.prepare('INSERT INTO guest_groups(id,event_id,name) VALUES(?,?,?)').bind(groupId!,id,g.group))}stmts.push(c.env.DB.prepare("INSERT INTO guests(id,event_id,group_id,name,status,party_size,meal,table_name,checked_in_at) VALUES(?,?,?,?,?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET group_id=excluded.group_id,name=excluded.name,status=excluded.status,party_size=excluded.party_size,meal=excluded.meal,table_name=excluded.table_name,checked_in_at=excluded.checked_in_at,updated_at=CURRENT_TIMESTAMP").bind(gid,id,groupId,g.name,g.status.toLowerCase(),g.party,g.meal==='—'?null:g.meal,g.table||null,g.checkedIn?nowIso():null))}if(stmts.length)await c.env.DB.batch(stmts);if(keep.length<=900)await c.env.DB.prepare(`DELETE FROM guests WHERE event_id=? AND id NOT IN (${keep.map(()=>'?').join(',')})`).bind(id,...keep).run();await audit(c.env.DB,id,c.get('userId'),'guests.sync','guest',null,c.get('requestId'),{count:keep.length});return c.json({ok:true,count:keep.length})});
app.put('/api/v1/events/:eventId/sections/sync',async c=>{const id=c.req.param('eventId');await ownEvent(c,id);const body=await json(c.req.raw,z.object({sections:z.array(z.object({title:z.string().trim().min(1).max(100),type:z.string().max(50).default('custom'),content:z.record(z.string(),z.unknown()).default({}),visible:z.boolean().default(true)})).max(50)}));const statements=[c.env.DB.prepare('DELETE FROM experience_sections WHERE event_id=?').bind(id),...body.sections.map((s,i)=>c.env.DB.prepare('INSERT INTO experience_sections(id,event_id,type,title,content_json,sort_order,is_visible) VALUES(?,?,?,?,?,?,?)').bind(uid('sec'),id,s.type,s.title,JSON.stringify(s.content),i,s.visible?1:0))];await c.env.DB.batch(statements);return c.json({ok:true,count:body.sections.length})});
app.put('/api/v1/events/:eventId/schedule/sync',async c=>{const id=c.req.param('eventId');await ownEvent(c,id);const body=await json(c.req.raw,z.object({schedule:z.array(scheduleSchema).max(100)}));const keep:string[]=[],stmts=[];for(let i=0;i<body.schedule.length;i++){const s=body.schedule[i],sid=s.id?(s.id.startsWith('occ_')?s.id:`occ_local_${s.id}`):uid('occ');keep.push(sid);stmts.push(c.env.DB.prepare("INSERT INTO occasions(id,event_id,title,starts_at,venue_name,address,audience,sort_order) VALUES(?,?,?,?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET title=excluded.title,starts_at=excluded.starts_at,venue_name=excluded.venue_name,address=excluded.address,audience=excluded.audience,sort_order=excluded.sort_order").bind(sid,id,s.title,`2026-12-19T${s.time}:00+01:00`,s.place,s.place,s.audience,i))}if(stmts.length)await c.env.DB.batch(stmts);if(keep.length)await c.env.DB.prepare(`DELETE FROM occasions WHERE event_id=? AND id NOT IN (${keep.map(()=>'?').join(',')})`).bind(id,...keep).run();return c.json({ok:true})});
app.post('/api/v1/events/:eventId/seating',async c=>{const id=c.req.param('eventId');await ownEvent(c,id);const body=await json(c.req.raw,z.object({name:z.string().trim().min(1).max(30),shape:z.enum(['round','rectangle','head']).default('round'),capacity:z.number().int().min(1).max(100),x:z.number().min(0).max(100).default(50),y:z.number().min(0).max(100).default(50)}));const rowId=uid('tbl');try{await c.env.DB.prepare('INSERT INTO seating_tables(id,event_id,name,shape,capacity,x,y) VALUES(?,?,?,?,?,?,?)').bind(rowId,id,body.name,body.shape,body.capacity,body.x,body.y).run()}catch{throw new HTTPException(409,{message:'A table with this name already exists'})}return c.json({id:rowId},201)});
app.delete('/api/v1/events/:eventId/seating/:tableId',async c=>{const id=c.req.param('eventId');await ownEvent(c,id);const table=await c.env.DB.prepare('SELECT name FROM seating_tables WHERE id=? AND event_id=?').bind(c.req.param('tableId'),id).first<any>();if(!table)throw new HTTPException(404,{message:'Table not found'});await c.env.DB.batch([c.env.DB.prepare('UPDATE guests SET table_name=NULL WHERE event_id=? AND table_name=?').bind(id,table.name),c.env.DB.prepare('DELETE FROM seating_tables WHERE id=? AND event_id=?').bind(c.req.param('tableId'),id)]);return c.body(null,204)});
app.patch('/api/v1/events/:eventId/guests/:guestId/seat',async c=>{const id=c.req.param('eventId');await ownEvent(c,id);const body=await json(c.req.raw,z.object({table:z.string().max(30).nullable()}));if(body.table){const guest=await c.env.DB.prepare('SELECT party_size FROM guests WHERE id=? AND event_id=?').bind(c.req.param('guestId'),id).first<any>();if(!guest)throw new HTTPException(404,{message:'Guest not found'});const table=await c.env.DB.prepare('SELECT capacity,(SELECT COALESCE(SUM(party_size),0) FROM guests WHERE event_id=? AND table_name=? AND id<>?) AS assigned FROM seating_tables WHERE event_id=? AND name=?').bind(id,body.table,c.req.param('guestId'),id,body.table).first<any>();if(!table)throw new HTTPException(404,{message:'Table not found'});if(Number(table.assigned)+Number(guest.party_size)>Number(table.capacity))throw new HTTPException(409,{message:'This party would exceed the table capacity'})}const result=await c.env.DB.prepare('UPDATE guests SET table_name=?,updated_at=CURRENT_TIMESTAMP WHERE id=? AND event_id=?').bind(body.table,c.req.param('guestId'),id).run();if(!result.meta.changes)throw new HTTPException(404,{message:'Guest not found'});return c.json({ok:true})});
app.post('/api/v1/events/:eventId/budgets',async c=>{const id=c.req.param('eventId');await ownEvent(c,id);const body=await json(c.req.raw,z.object({category:z.string().trim().min(2).max(100),budget:z.number().nonnegative().max(100000000000),spent:z.number().nonnegative().max(100000000000).default(0),currency:z.string().length(3).default('NGN')}));if(body.spent>body.budget*2&&body.budget>0)throw new HTTPException(422,{message:'Spent amount needs confirmation because it greatly exceeds budget'});const rowId=uid('bdg');await c.env.DB.prepare('INSERT INTO budgets(id,event_id,category,budget_minor,spent_minor,currency) VALUES(?,?,?,?,?,?)').bind(rowId,id,body.category,Math.round(body.budget*100),Math.round(body.spent*100),body.currency).run();return c.json({id:rowId},201)});
app.delete('/api/v1/events/:eventId/budgets/:budgetId',async c=>{const id=c.req.param('eventId');await ownEvent(c,id);await c.env.DB.prepare('DELETE FROM budgets WHERE id=? AND event_id=?').bind(c.req.param('budgetId'),id).run();return c.body(null,204)});
app.post('/api/v1/events/:eventId/vendors',async c=>{const id=c.req.param('eventId');await ownEvent(c,id);const body=await json(c.req.raw,z.object({name:z.string().trim().min(2).max(140),category:z.string().trim().min(2).max(100),email:z.string().email().optional().or(z.literal('')),phone:z.string().max(40).optional(),amount:z.number().nonnegative().max(100000000000).default(0),status:z.enum(['due','part_paid','paid']).default('due')}));const rowId=uid('vnd');await c.env.DB.prepare('INSERT INTO vendors(id,event_id,name,category,email,phone,contract_amount_minor,payment_status) VALUES(?,?,?,?,?,?,?,?)').bind(rowId,id,body.name,body.category,body.email||null,body.phone||null,Math.round(body.amount*100),body.status).run();return c.json({id:rowId},201)});
app.delete('/api/v1/events/:eventId/vendors/:vendorId',async c=>{const id=c.req.param('eventId');await ownEvent(c,id);await c.env.DB.prepare('DELETE FROM vendors WHERE id=? AND event_id=?').bind(c.req.param('vendorId'),id).run();return c.body(null,204)});
app.post('/api/v1/events/:eventId/announcements',async c=>{const id=c.req.param('eventId');await ownEvent(c,id);const body=await json(c.req.raw,announcementSchema),jobId=uid('msg');await c.env.DB.prepare('INSERT INTO announcements(id,event_id,created_by,channel,audience,message) VALUES(?,?,?,?,?,?)').bind(jobId,id,c.get('userId'),body.channel,body.audience,body.message).run();const job:NotificationJob={id:jobId,eventId:id,...body,createdAt:nowIso()};await c.env.NOTIFICATIONS.send(job);return c.json({ok:true,id:jobId,status:'queued'},202)});
app.post('/api/v1/events/:eventId/checkin/scan',async c=>{const id=c.req.param('eventId');await ownEvent(c,id);const body=await json(c.req.raw,z.object({token:z.string().min(20).max(200)}));const guest=await c.env.DB.prepare('SELECT id,name,party_size,table_name,checked_in_at FROM guests WHERE event_id=? AND access_token_hash=?').bind(id,await sha256(body.token)).first<any>();if(!guest)throw new HTTPException(404,{message:'This pass is not valid for this event'});if(!guest.checked_in_at)await c.env.DB.prepare('UPDATE guests SET checked_in_at=CURRENT_TIMESTAMP WHERE id=?').bind(guest.id).run();return c.json({guest:{id:guest.id,name:guest.name,party:guest.party_size,table:guest.table_name},alreadyCheckedIn:Boolean(guest.checked_in_at)})});
app.patch('/api/v1/events/:eventId/guests/:guestId/checkin',async c=>{const id=c.req.param('eventId');await ownEvent(c,id);const body=await json(c.req.raw,z.object({checkedIn:z.boolean()}));const result=await c.env.DB.prepare('UPDATE guests SET checked_in_at=?,updated_at=CURRENT_TIMESTAMP WHERE id=? AND event_id=?').bind(body.checkedIn?nowIso():null,c.req.param('guestId'),id).run();if(!result.meta.changes)throw new HTTPException(404,{message:'Guest not found'});return c.json({ok:true,checkedIn:body.checkedIn})});
app.post('/api/v1/events/:eventId/media',async c=>{const id=c.req.param('eventId');await ownEvent(c,id);const form=await c.req.formData(),file=form.get('file');if(!(file instanceof File))throw new HTTPException(400,{message:'File is required'});const allowed=['image/jpeg','image/png','image/webp','video/mp4','audio/mpeg'];if(!allowed.includes(file.type)||file.size>25*1024*1024)throw new HTTPException(415,{message:'Unsupported file type or file exceeds 25 MB'});const key=`events/${id}/${uid('media')}-${file.name.replace(/[^a-zA-Z0-9._-]/g,'_')}`;await c.env.MEDIA.put(key,file.stream(),{httpMetadata:{contentType:file.type}});const mediaId=uid('med');await c.env.DB.prepare('INSERT INTO media(id,event_id,object_key,mime_type,size_bytes,caption) VALUES(?,?,?,?,?,?)').bind(mediaId,id,key,file.type,file.size,String(form.get('caption')||'').slice(0,500)).run();return c.json({id:mediaId,status:'pending'},201)});

app.get('/api/v1/events/:eventId/media/:mediaId/file',async c=>{const id=c.req.param('eventId');await ownEvent(c,id);const row=await c.env.DB.prepare('SELECT object_key,mime_type FROM media WHERE id=? AND event_id=?').bind(c.req.param('mediaId'),id).first<any>();if(!row)throw new HTTPException(404,{message:'Media not found'});const object=await c.env.MEDIA.get(row.object_key);if(!object)throw new HTTPException(404,{message:'Stored media not found'});return new Response(object.body,{headers:{'Content-Type':row.mime_type,'Cache-Control':'private, max-age=300','X-Content-Type-Options':'nosniff'}})});
app.patch('/api/v1/events/:eventId/media/:mediaId',async c=>{const id=c.req.param('eventId');await ownEvent(c,id);const body=await json(c.req.raw,z.object({status:z.enum(['pending','approved','rejected'])}));const result=await c.env.DB.prepare('UPDATE media SET status=? WHERE id=? AND event_id=?').bind(body.status,c.req.param('mediaId'),id).run();if(!result.meta.changes)throw new HTTPException(404,{message:'Media not found'});return c.json({ok:true})});
app.get('/api/v1/public/events/:slug',async c=>{const event=await c.env.DB.prepare("SELECT id,slug,title,event_type,starts_at,timezone,location,theme_json,settings_json FROM events WHERE slug=? AND lifecycle IN ('published','active','live','completed')").bind(c.req.param('slug')).first<any>();if(!event)throw new HTTPException(404,{message:'Invitation not found'});const token=c.req.query('token');let guest=null;if(token){guest=await c.env.DB.prepare('SELECT id,name,party_size,status,table_name FROM guests WHERE event_id=? AND access_token_hash=?').bind(event.id,await sha256(token)).first()}const occasions=guest?await c.env.DB.prepare('SELECT o.id,o.title,o.starts_at,o.venue_name,o.address,a.rsvp_status FROM occasions o JOIN guest_occasion_access a ON a.occasion_id=o.id WHERE a.guest_id=? ORDER BY o.sort_order').bind((guest as any).id).all():await c.env.DB.prepare('SELECT id,title,starts_at,venue_name,address FROM occasions WHERE event_id=? AND is_private=0 ORDER BY sort_order').bind(event.id).all();return c.json({event:{...event,theme:JSON.parse(event.theme_json),settings:JSON.parse(event.settings_json)},guest,occasions:occasions.results})});
app.post('/api/v1/public/rsvp',async c=>{const body=await json(c.req.raw,rsvpSchema),tokenHash=await sha256(body.token);const guest=await c.env.DB.prepare('SELECT id,event_id FROM guests WHERE access_token_hash=?').bind(tokenHash).first<any>();if(!guest)throw new HTTPException(401,{message:'Invitation link is invalid or expired'});const key=c.req.header('Idempotency-Key')||await sha256(JSON.stringify(body));const prior=await c.env.DB.prepare('SELECT id FROM rsvp_submissions WHERE guest_id=? AND idempotency_key=?').bind(guest.id,key).first();if(prior)return c.json({ok:true,replayed:true});const allowed=await c.env.DB.prepare('SELECT occasion_id FROM guest_occasion_access WHERE guest_id=?').bind(guest.id).all<any>();const set=new Set(allowed.results.map(x=>x.occasion_id));if(body.responses.some(x=>!set.has(x.occasionId)))throw new HTTPException(403,{message:'RSVP contains an occasion not assigned to this guest'});const overall=body.responses.some(x=>x.status==='attending')?'attending':'declined';const stmts=[c.env.DB.prepare('UPDATE guests SET status=?,dietary_notes=?,plus_one_name=?,updated_at=CURRENT_TIMESTAMP WHERE id=?').bind(overall,body.dietaryNotes||null,body.plusOneName||null,guest.id),c.env.DB.prepare('INSERT INTO rsvp_submissions(id,guest_id,idempotency_key,payload_hash) VALUES(?,?,?,?)').bind(uid('rsvp'),guest.id,key,await sha256(JSON.stringify(body)))];for(const r of body.responses)stmts.push(c.env.DB.prepare('UPDATE guest_occasion_access SET rsvp_status=?,meal=?,updated_at=CURRENT_TIMESTAMP WHERE guest_id=? AND occasion_id=?').bind(r.status,r.meal||null,guest.id,r.occasionId));await c.env.DB.batch(stmts);return c.json({ok:true,status:overall})});
app.post('/api/v1/public/payments/paystack/initialize',rateLimit,async c=>{if(!c.env.PAYSTACK_SECRET_KEY)throw new HTTPException(503,{message:'Gift payments are not configured for this environment'});const body=await json(c.req.raw,z.object({slug:z.string().min(2).max(100),token:z.string().max(200).optional(),email:z.string().email(),amount:z.number().min(100).max(100000000),purpose:z.enum(['gift','ticket','contribution','asoebi']).default('gift')}));const event=await c.env.DB.prepare("SELECT id,title FROM events WHERE slug=? AND lifecycle IN ('published','active','live')").bind(body.slug).first<any>();if(!event)throw new HTTPException(404,{message:'Event is not accepting payments'});let guestId=null;if(body.token){const guest=await c.env.DB.prepare('SELECT id FROM guests WHERE event_id=? AND access_token_hash=?').bind(event.id,await sha256(body.token)).first<any>();if(!guest)throw new HTTPException(403,{message:'Invalid guest invitation'});guestId=guest.id}const reference=uid('pay'),paymentId=uid('pmt'),amountMinor=Math.round(body.amount*100);await c.env.DB.prepare("INSERT INTO payments(id,event_id,guest_id,provider,reference,purpose,amount_minor,status) VALUES(?,?,?,'paystack',?,?,?,'pending')").bind(paymentId,event.id,guestId,reference,body.purpose,amountMinor).run();const response=await fetch('https://api.paystack.co/transaction/initialize',{method:'POST',headers:{Authorization:`Bearer ${c.env.PAYSTACK_SECRET_KEY}`,'Content-Type':'application/json'},body:JSON.stringify({email:body.email,amount:amountMinor,currency:'NGN',reference,metadata:{event_id:event.id,payment_id:paymentId,purpose:body.purpose}})});const result:any=await response.json();if(!response.ok||!result.status){await c.env.DB.prepare("UPDATE payments SET status='failed',updated_at=CURRENT_TIMESTAMP WHERE id=?").bind(paymentId).run();throw new HTTPException(502,{message:'Payment provider could not initialize checkout'})}await c.env.DB.prepare("UPDATE payments SET status='initialized',checkout_url=?,updated_at=CURRENT_TIMESTAMP WHERE id=?").bind(result.data.authorization_url,paymentId).run();return c.json({paymentId,reference,checkoutUrl:result.data.authorization_url},201)});
app.post('/api/v1/webhooks/paystack',async c=>{if(!c.env.PAYSTACK_SECRET_KEY)throw new HTTPException(503,{message:'Payment webhook is not configured'});const raw=await c.req.text(),provided=c.req.header('x-paystack-signature')||'',expected=await hmacSha512(c.env.PAYSTACK_SECRET_KEY,raw);if(provided.length!==expected.length||!provided.split('').every((ch,i)=>ch===expected[i]))throw new HTTPException(401,{message:'Invalid webhook signature'});const payload=JSON.parse(raw);const providerId=String(payload.data?.id||payload.data?.reference||uid('hook'));const inserted=await c.env.DB.prepare('INSERT OR IGNORE INTO webhook_events(id,provider,provider_event_id,event_type,payload_hash) VALUES(?,?,?,?,?)').bind(uid('wh'),'paystack',providerId,String(payload.event),await sha256(raw)).run();if(!inserted.meta.changes)return c.json({ok:true,replayed:true});if(payload.event==='charge.success')await c.env.DB.prepare("UPDATE payments SET status='paid',paid_at=CURRENT_TIMESTAMP,updated_at=CURRENT_TIMESTAMP WHERE reference=? AND amount_minor=?").bind(String(payload.data.reference),Number(payload.data.amount)).run();return c.json({ok:true})});
app.post('/api/v1/public/analytics',async c=>{const body=await json(c.req.raw,z.object({eventId:z.string(),type:z.enum(['view','section_view','share','calendar','direction']),session:z.string().max(100).optional(),metadata:z.record(z.string(),z.unknown()).optional()}));await c.env.DB.prepare('INSERT INTO analytics_events(id,event_id,type,session_hash,metadata_json) VALUES(?,?,?,?,?)').bind(uid('an'),body.eventId,body.type,body.session?await sha256(body.session):null,JSON.stringify(body.metadata||{})).run();return c.body(null,204)});

app.notFound(c=>c.json({error:{code:'NOT_FOUND',message:'Route not found'},requestId:c.get('requestId')},404));
app.onError((err,c)=>{console.error(JSON.stringify({level:'error',requestId:c.get('requestId'),message:err.message}));if(err instanceof ZodError)return c.json({error:{code:'VALIDATION_ERROR',message:'The request contains invalid data',issues:err.issues},requestId:c.get('requestId')},422);if(err instanceof HTTPException)return c.json({error:{code:`HTTP_${err.status}`,message:err.message},requestId:c.get('requestId')},err.status);return c.json({error:{code:'INTERNAL_ERROR',message:'An unexpected error occurred'},requestId:c.get('requestId')},500)});

export default {fetch:app.fetch,async queue(batch:MessageBatch<NotificationJob>,env:AppEnv['Bindings']){for(const msg of batch.messages){try{await env.DB.prepare("UPDATE announcements SET status='failed' WHERE id=?").bind(msg.body.id).run();console.warn(JSON.stringify({level:'warn',code:'PROVIDER_NOT_CONFIGURED',jobId:msg.body.id,channel:msg.body.channel}));msg.ack()}catch(error){console.error('notification_job_failed',msg.body.id,error);msg.retry()}}},async scheduled(_event:ScheduledEvent,env:AppEnv['Bindings']){await env.DB.prepare("DELETE FROM sessions WHERE expires_at < datetime('now')").run()}};
;
