import { createContext, useContext, useEffect, useRef, useState } from 'react';
import type { Dispatch, ReactNode, SetStateAction } from 'react';
import { initialGuests, initialSchedule } from './data';
import type { Guest, ScheduleItem } from './types';
import { api } from './api';

type Phase='loading'|'ready'|'auth'|'onboarding';
export type EventRecord={id:string;slug:string;title:string;event_type:string;lifecycle:string;starts_at:string;timezone:string;location:string;visibility?:string;settings_json?:string;theme_json?:string};
export type MediaRecord={id:string;mime_type:string;size_bytes:number;caption?:string;status:'pending'|'approved'|'rejected';created_at:string};export type SeatingRecord={id:string;name:string;shape:string;capacity:number;x:number;y:number;assigned:number};export type BudgetRecord={id:string;category:string;budget_minor:number;spent_minor:number;currency:string};export type VendorRecord={id:string;name:string;category:string;email?:string;phone?:string;contract_amount_minor:number;payment_status:'due'|'part_paid'|'paid'};
type Store={analytics:Record<string,number>;media:MediaRecord[];seating:SeatingRecord[];budgets:BudgetRecord[];vendors:VendorRecord[];sections:string[];setSections:Dispatch<SetStateAction<string[]>>;guests:Guest[];setGuests:Dispatch<SetStateAction<Guest[]>>;schedule:ScheduleItem[];setSchedule:Dispatch<SetStateAction<ScheduleItem[]>>;eventId:string;event:EventRecord|null;events:EventRecord[];online:boolean;loading:boolean;error:string|null;phase:Phase;authenticate:(mode:'login'|'register',data:{name?:string,email:string,password:string})=>Promise<void>;createFirst:(data:{title:string,eventType:string,date:string,location:string})=>Promise<void>;switchEvent:(id:string)=>Promise<void>;logout:()=>Promise<void>;refresh:()=>Promise<void>};
const Context=createContext<Store|null>(null);
function cached<T>(key:string,fallback:T):T{try{return JSON.parse(localStorage.getItem(key)||'null')||fallback}catch{return fallback}}
export function EventStoreProvider({children}:{children:ReactNode}){
 const [sections,setSections]=useState<string[]>(['Welcome','Our story','Event details','Schedule','Gallery','RSVP','Gift registry','FAQ']);const [guests,setGuests]=useState<Guest[]>(()=>cached('invibox.guests',initialGuests));const [schedule,setSchedule]=useState<ScheduleItem[]>(()=>cached('invibox.schedule',initialSchedule));
 const [analytics,setAnalytics]=useState<Record<string,number>>({});const [media,setMedia]=useState<MediaRecord[]>([]);const [seating,setSeating]=useState<SeatingRecord[]>([]);const [budgets,setBudgets]=useState<BudgetRecord[]>([]);const [vendors,setVendors]=useState<VendorRecord[]>([]);
 const [eventId,setEventId]=useState(()=>localStorage.getItem('invibox.eventId')||'');const [event,setEvent]=useState<EventRecord|null>(null);const [events,setEvents]=useState<EventRecord[]>([]);const [online,setOnline]=useState(false);const [phase,setPhase]=useState<Phase>('loading');const [error,setError]=useState<string|null>(null);const hydrated=useRef(false);
 const load=async(id:string)=>{hydrated.current=false;const snap=await api.snapshot(id);setEventId(id);setEvent(snap.event as EventRecord);localStorage.setItem('invibox.eventId',id);setGuests(snap.guests);setSchedule(snap.schedule);setAnalytics(snap.analytics||{});setMedia(snap.media||[]);setSeating(snap.seating||[]);setBudgets(snap.budgets||[]);setVendors(snap.vendors||[]);setSections(snap.sections?.length?snap.sections.map((x:{title?:string,type:string})=>x.title||x.type):['Welcome','Event details','Schedule','RSVP']);setOnline(true);setError(null);setPhase('ready');setTimeout(()=>{hydrated.current=true},0)};
 const loadAccount=async()=>{const result=await api.events();setEvents(result.events);if(!result.events.length){setOnline(true);setPhase('onboarding');return}const preferred=localStorage.getItem('invibox.eventId');const selected=result.events.find((x:EventRecord)=>x.id===preferred)||result.events[0];await load(selected.id)};
 useEffect(()=>{let active=true;(async()=>{try{await api.me();if(active)await loadAccount()}catch{try{const boot=await api.bootstrap();if(!active)return;localStorage.setItem('invibox.guestToken',boot.guestToken);await loadAccount();await load(boot.eventId)}catch(e){if(active){setError(e instanceof Error?e.message:'Sign in required');setOnline(false);setPhase('auth')}}}})();return()=>{active=false}},[]);
 const authenticate=async(mode:'login'|'register',data:{name?:string,email:string,password:string})=>{setError(null);try{if(mode==='login')await api.login(data.email,data.password);else await api.register(data.name||'',data.email,data.password);await loadAccount()}catch(e){setError(e instanceof Error?e.message:'Authentication failed');throw e}};
 const createFirst=async(data:{title:string,eventType:string,date:string,location:string})=>{const result=await api.createEvent({...data,timezone:'Africa/Lagos'});await loadAccount();await load(result.event.id)};
 const logout=async()=>{await api.logout();localStorage.removeItem('invibox.eventId');localStorage.removeItem('invibox.guestToken');setEvent(null);setEvents([]);setEventId('');setPhase('auth');setOnline(false)};
 const switchEvent=async(id:string)=>{if(id===eventId)return;setPhase('loading');try{await load(id)}catch(e){setError(e instanceof Error?e.message:'Could not open event');setPhase('ready')}};
 useEffect(()=>{localStorage.setItem('invibox.guests',JSON.stringify(guests));if(!hydrated.current||!eventId||!online)return;const t=setTimeout(()=>api.syncGuests(eventId,guests).catch(()=>setOnline(false)),350);return()=>clearTimeout(t)},[guests,eventId,online]);
 useEffect(()=>{if(!hydrated.current||!eventId||!online)return;const t=setTimeout(()=>api.syncSections(eventId,sections.map(title=>({title,type:title.toLowerCase().replaceAll(' ','_'),content:{},visible:true}))).catch(()=>setOnline(false)),450);return()=>clearTimeout(t)},[sections,eventId,online]);
 useEffect(()=>{localStorage.setItem('invibox.schedule',JSON.stringify(schedule));if(!hydrated.current||!eventId||!online)return;const t=setTimeout(()=>api.syncSchedule(eventId,schedule).catch(()=>setOnline(false)),350);return()=>clearTimeout(t)},[schedule,eventId,online]);
 return <Context.Provider value={{analytics,media,seating,budgets,vendors,sections,setSections,guests,setGuests,schedule,setSchedule,eventId,event,events,online,loading:phase==='loading',error,phase,authenticate,createFirst,switchEvent,logout,refresh:loadAccount}}>{children}</Context.Provider>
}
export function useEventStore(){const c=useContext(Context);if(!c)throw new Error('Event store provider missing');return c}
